name: Deploy

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Git Pull
        run: |
          cd ${{ github.workspace }}
          ssh-keyscan -t rsa ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "cd berke.in && git pull origin production"

      - name: Restart Containers
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "cd berke.in && docker compose down --rmi all -v && docker compose up -d"
